# Problema

Vamos treinar a rede neural de forma que ela possa prever o valor de saída correto quando fornecida com um novo conjunto de dados.

In [1]:
import numpy as np

In [5]:
#Matrix (4x3)
treinamento_entrada = np.array([[0, 0, 1],
                                [1, 1, 1], 
                                [1, 0, 1], 
                                [0, 1, 1],])

In [6]:
type(treinamento_entrada)

numpy.ndarray

In [7]:
treinamento_entrada

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [8]:
treinamento_resultado = np.array([[0, 1, 1, 0]]).T

In [ ]:
treinamento_resultado

In [9]:
np.random.seed(1)

In [10]:
pesos_sinapticos = 2 * np.random.random((3,1)) - 1

In [11]:
pesos_sinapticos

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [12]:
def sigmoid(x):
  return 1/(1 + np.exp(-x))

In [13]:
def sigmoid_derivate(x):
  return x * (1-x)

In [14]:
for i in range(10000):
  input_layer = treinamento_entrada
  output = sigmoid(np.dot(input_layer, pesos_sinapticos))

  erro = treinamento_resultado - output
  ajuste = erro * sigmoid_derivate(output)

  pesos_sinapticos += np.dot(input_layer.T, ajuste)

In [15]:
pesos_sinapticos

array([[ 9.67299303],
       [-0.2078435 ],
       [-4.62963669]])

In [16]:
print(output)

[[0.00966449]
 [0.99211957]
 [0.99358898]
 [0.00786506]]


In [ ]:
0, 1, 1, 0

In [17]:
# Nova situação para prever o dado de saída
nova_situacao = np.array([1, 0, 0])
nova_situacao = np.reshape(nova_situacao, (1, 3))

In [18]:
# Predição do dado de saída
predicao = sigmoid(np.dot(nova_situacao, pesos_sinapticos))

In [19]:
print(predicao)

[[0.99993704]]
